name: zpretty
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]

    steps:
      # git checkout
      - uses: actions/checkout@v2

      # python setup
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # python cache
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # install zpretty
      - name: install zpretty
        run: pip install zpretty

      - name: run zpretty for zcml
        run: find plone -name '*.zcml' | xargs zpretty -z --check

      - name: run zpretty for xml
        run: find plone -name '*.xml' | xargs zpretty -x --check
